### PR TITLE
Feature/stars

### PR DESCRIPTION
**Pull request by lauranenart**
Padariau vertinimo sistemą, peržiūrėk ir pasakyk ar ko trūksta

### CODE REVIEW

**Comment by ValdasVabolis** [comment]
Looks like there's a bug where if the user refreshes the page after voting, the vote disappears. Need to implement a check if user voted for a particular post and then display the vote if true.

**Comment by ValdasVabolis** [comment]
Also, try to move out the <script> tag out of cshtml file to avoid cluttering. Either move it to site.js or a separate file. Other than that, progress is looking solid so far!

**Comment by lauranenart** [comment]
> Looks like there's a bug where if the user refreshes the page after voting, the vote disappears. Need to implement a check if user voted for a particular post and then display the vote if true.

taip, ačiū, visai pamiršau apie tai

**Comment by lauranenart** [comment]
> Also, try to move out the <script> tag out of cshtml file to avoid cluttering. Either move it to site.js or a separate file. Other than that, progress is looking solid so far!

okey, perkelsiu

**Comment by lauranenart** [comment]
@ValdasVabolis taip pat, pamiršau dar paminėti, kad ER diagramą papildyk naujais attributais Total, Rating bei Quantity

**Comment by ValdasVabolis** [comment]
> @ValdasVabolis taip pat, pamiršau dar paminėti, kad ER diagramą papildyk naujais attributais Total, Rating bei Quantity

Good notice, will do

**Pull request merged**
